// <auto-generated />
using System;
using Hospital_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260801160813_datafordoctors")]
    partial class datafordoctors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_Management_System.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppoitmentTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "1.jpg",
                            Name = "Dr. Ahmed Hassan",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Image = "2.jpg",
                            Name = "Dr. Sara Mohamed",
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            Id = 3,
                            Image = "3.jpg",
                            Name = "Dr. Omar Ali",
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = 4,
                            Image = "4.jpg",
                            Name = "Dr. Mariam Ibrahim",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 5,
                            Image = "5.jpg",
                            Name = "Dr. Youssef Mahmoud",
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = 6,
                            Image = "6.jpg",
                            Name = "Dr. Nour El Din",
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = 7,
                            Image = "7.jpg",
                            Name = "Dr. Fatma Khaled",
                            Specialization = "Gynecology"
                        },
                        new
                        {
                            Id = 8,
                            Image = "8.jpg",
                            Name = "Dr. Karim Mostafa",
                            Specialization = "General Surgery"
                        },
                        new
                        {
                            Id = 9,
                            Image = "9.jpg",
                            Name = "Dr. Reem Adel",
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            Id = 10,
                            Image = "10.jpg",
                            Name = "Dr. Hany Fawzy",
                            Specialization = "Cardiology"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Appointment", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
